#!/usr/bin/env bash
# Configure nginx to have 404 page
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '26 i \         rewrite ^/redirect_me httpsL//google.com permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo service nginx restart
