#!/bin/bash
# create back up of mysql database and compress into tar file
DATE=$(date +%d-%m-%Y)
PASSWORD=$1
mysqldump -uroot -p"$PASSWORD" --all-databases > backup.sql
tar -czvf "$DATE.tar.gz" backup.sql
