#!/usr/bin/env bash
# prints string indefinitely
sudo bash -c "echo '$$' > /var/run/holbertonscript.pid"
while true
do
    echo To infinity and beyond
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm -rf /var/run/holbertonscript.pid ;echo "I hate the kill command" ;exit' SIGTERM SIGQUIT
    sleep 2
done
