#!/usr/bin/env bash
# prints string indefinitely
sudo bash -c "echo '$$' > /var/run/holbertonscript.pid"
while true
do
    echo To infinity and beyond
    trap 'echo "I hate the kill command"' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'rm /var/run/holbertonscript.pid' SIGQUIT SIGTERM
    sleep 2
done
