#!/usr/bin/env bash
# print fizzbuzz

counter=1
while [ $counter -lt 101 ]
do
	if ((counter % 5 == 0)) && ((counter % 3 == 0))
	then
	    echo FizzBuzz
	elif ((counter % 5 == 0))
	then 
	    echo Buzz
	elif ((counter % 3 == 0))
	then
	    echo Fizz
	else
	    echo "$counter"
	fi
	((counter++))
done
