#!/usr/bin/env bash
# prints holberton school 10 times and hi on the 9th

counter=1
while [ $counter -le 10 ]
do
    echo Holberton School
    if [ $counter -eq 9 ]
    then
	echo Hi
    fi
    ((counter++))
done
