#!/usr/bin/env bash
# configure web-02 identical to web-01
# shellcheck disable=SC2016
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "37 i \            add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
